simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  left_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge
    pid: {p: 3.0, i: 0.1, d: 0.4}
  right_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge
    pid: {p: 3.0, i: 0.1, d: 0.4}
  lower_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: lower_arm_hinge
    pid: {p: 20.0, i: 1.0, d: 4.0}
  upper_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: upper_arm_hinge
    pid: {p: 20.0, i: 1.0, d: 4.0} 