controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_wheel_hinge
      - right_wheel_hinge
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity